export const USER = {
  NAME_MIN_LENGTH: 5,
  NAME_MAX_LENGTH: 50,
  EMAIL_MIN_LENGTH: 5,
  EMAIL_MAX_LENGTH: 100,
  PASSWORD_MIN_LENGTH: 8,
  PASSWORD_MAX_LENGTH: 128,
  ROLES: ["admin", "client"],
} as const;
